
name: DeployApplication
on: [push, workflow_dispatch] # Triggered by push or manual dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4 # Updated to v4
      - name: Install NodeJS
        uses: actions/setup-node@v4 # Updated to v4
        with: 
          node-version: 24
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:       
    needs: test. # test has to be successful before deploy can start
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4 # Updated to v4
      - name: Install NodeJS
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: 24
      - name: Install Dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy to server
        run: echo "Deploying application to server..."