name: Output information  
on:  workflow_dispatch
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
    - name: Output GitHub Context
      run: |
        echo "${{ toJSON(github) }}"
        echo "${{ toJSON(github.event_name) }}"